[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.26"

[features]
seeds = false
init-if-needed = false

[programs.devnet]
ecosystem_token = "11111111111111111111111111111112"

[programs.mainnet]
ecosystem_token = "11111111111111111111111111111112"

[registry]
url = "https://api.anchor-lang.com/api/registry"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --lib"
