[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.10"

[features]
seeds = false
init-if-needed = false

[programs.devnet]
ecosystem_token = "11111111111111111111111111111112"

[programs.mainnet]
ecosystem_token = "11111111111111111111111111111112"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --lib"
